name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '5.0.x'

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --logger trx --results-directory "TestResults-${{ env.DOTNET_VERSION }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-results-${{ env.DOTNET_VERSION }}
          path: TestResults-${{ env.DOTNET_VERSION }}
        if: ${{ always() }}

      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-package-${{ env.DOTNET_VERSION }}
          path: "*.Package/bin/Release/*.nupkg"